Repository googleapis/google-api-go-client, pull requests merged in 2021-03, with the labels that each got.

#905 chore: make renovate act weekly again
  .github/renovate.json
Labels: automerge, cla: yes

#908 test: Create Integration Test for BYOID
  integration-tests/byoid/integration_test.go
  integration-tests/byoid/setup.sh
Labels: automerge, cla: yes

#914 chore: update generator to use 1.16
  internal/kokoro/synth/synth.sh
Labels: automerge, cla: yes

#919 test: add support for sourcing secrets from secret manager
  integration-tests/idtoken/idtoken_test.go
  internal/kokoro/populate-secrets.sh
  internal/kokoro/test.sh
  internal/kokoro/trampoline.sh
Labels: cla: yes

#921 test: refactor idtoken test
  idtoken/integration_test.go
  internal/kokoro/test.sh
Labels: automerge, cla: yes

#928 docs: fix syntax error of the example of inspecting errors
  doc.go
Labels: automerge: exact, cla: yes

#927 feat: add impersonate pacakge
  impersonate/doc.go
  impersonate/example_test.go
  impersonate/idtoken.go
  impersonate/idtoken_test.go
  impersonate/impersonate.go
  impersonate/impersonate_test.go
  impersonate/integration_test.go
  impersonate/user.go
  impersonate/user_test.go
  internal/kokoro/test.sh
  option/option.go
Labels: cla: yes

#949 chore: release v0.44.0-impersonate-preview
  CHANGES.md
Labels: cla: yes
