Repository googleapis/google-api-go-client, pull requests merged in 2023-11, with the labels that each got.

#2243 feat(all): auto-regenerate discovery clients
  api-list.json
  chromeuxreport/v1/chromeuxreport-api.json
  chromeuxreport/v1/chromeuxreport-gen.go
  contactcenterinsights/v1/contactcenterinsights-api.json
  contactcenterinsights/v1/contactcenterinsights-gen.go
  content/v2.1/content-api.json
  content/v2.1/content-gen.go
  iam/v1/iam-api.json
  iam/v1/iam-gen.go
  storage/v1/storage-api.json
  storage/v1/storage-gen.go
  testing/v1/testing-api.json
  testing/v1/testing-gen.go
  trafficdirector/v3/trafficdirector-api.json
  trafficdirector/v3/trafficdirector-gen.go
Labels: automerge: exact

#2249 feat(all): auto-regenerate discovery clients
  alloydb/v1/alloydb-api.json
  alloydb/v1/alloydb-gen.go
  alloydb/v1alpha/alloydb-api.json
  alloydb/v1alpha/alloydb-gen.go
  alloydb/v1beta/alloydb-api.json
  alloydb/v1beta/alloydb-gen.go
  artifactregistry/v1/artifactregistry-api.json
  artifactregistry/v1/artifactregistry-gen.go
  artifactregistry/v1beta1/artifactregistry-api.json
  artifactregistry/v1beta1/artifactregistry-gen.go
  artifactregistry/v1beta2/artifactregistry-api.json
  artifactregistry/v1beta2/artifactregistry-gen.go
  batch/v1/batch-api.json
  batch/v1/batch-gen.go
  beyondcorp/v1alpha/beyondcorp-api.json
  beyondcorp/v1alpha/beyondcorp-gen.go
  bigtableadmin/v2/bigtableadmin-api.json
  bigtableadmin/v2/bigtableadmin-gen.go
  clouddeploy/v1/clouddeploy-api.json
  clouddeploy/v1/clouddeploy-gen.go
  container/v1/container-api.json
  container/v1/container-gen.go
  datamigration/v1/datamigration-api.json
  datamigration/v1/datamigration-gen.go
  datastream/v1/datastream-api.json
  datastream/v1/datastream-gen.go
  firestore/v1/firestore-api.json
  firestore/v1/firestore-gen.go
  gkehub/v1/gkehub-api.json
  gkehub/v1/gkehub-gen.go
  gkehub/v1alpha/gkehub-api.json
  gkehub/v1alpha/gkehub-gen.go
  gkehub/v1beta/gkehub-api.json
  gkehub/v1beta/gkehub-gen.go
  logging/v2/logging-api.json
  logging/v2/logging-gen.go
Labels: automerge: exact

#2250 feat(all): auto-regenerate discovery clients
  container/v1beta1/container-api.json
  container/v1beta1/container-gen.go
Labels: automerge: exact

#2252 feat(all): auto-regenerate discovery clients
  connectors/v1/connectors-api.json
  connectors/v1/connectors-gen.go
Labels: automerge: exact

#2225 feat(transport): Log DirectPath misconfiguration
  go.mod
  go.sum
  transport/grpc/dial.go
  transport/grpc/dial_test.go
Labels: automerge

#2256 feat(all): auto-regenerate discovery clients
  androidenterprise/v1/androidenterprise-api.json
  androidenterprise/v1/androidenterprise-gen.go
  assuredworkloads/v1/assuredworkloads-api.json
  assuredworkloads/v1/assuredworkloads-gen.go
  cloudasset/v1/cloudasset-api.json
  cloudasset/v1/cloudasset-gen.go
  clouderrorreporting/v1beta1/clouderrorreporting-api.json
  dataplex/v1/dataplex-api.json
  dataplex/v1/dataplex-gen.go
  gmail/v1/gmail-api.json
  gmail/v1/gmail-gen.go
  playintegrity/v1/playintegrity-api.json
  playintegrity/v1/playintegrity-gen.go
  retail/v2/retail-api.json
  retail/v2/retail-gen.go
  retail/v2alpha/retail-api.json
  retail/v2alpha/retail-gen.go
  retail/v2beta/retail-api.json
  retail/v2beta/retail-gen.go
Labels: automerge: exact

#2257 feat(all): auto-regenerate discovery clients
  appengine/v1/appengine-api.json
  appengine/v1/appengine-gen.go
  appengine/v1beta/appengine-api.json
  appengine/v1beta/appengine-gen.go
  chromemanagement/v1/chromemanagement-api.json
  chromemanagement/v1/chromemanagement-gen.go
  cloudbuild/v1/cloudbuild-api.json
  cloudbuild/v1/cloudbuild-gen.go
  cloudbuild/v2/cloudbuild-api.json
  cloudbuild/v2/cloudbuild-gen.go
  fitness/v1/fitness-api.json
  manufacturers/v1/manufacturers-api.json
  manufacturers/v1/manufacturers-gen.go
  pubsub/v1/pubsub-api.json
  pubsub/v1/pubsub-gen.go
Labels: automerge: exact

#2259 feat(all): auto-regenerate discovery clients
  alloydb/v1/alloydb-api.json
  alloydb/v1/alloydb-gen.go
  artifactregistry/v1/artifactregistry-api.json
  artifactregistry/v1/artifactregistry-gen.go
  clouddeploy/v1/clouddeploy-api.json
  clouddeploy/v1/clouddeploy-gen.go
  datamigration/v1/datamigration-api.json
  datamigration/v1/datamigration-gen.go
  firestore/v1/firestore-api.json
  firestore/v1/firestore-gen.go
  gkehub/v1/gkehub-api.json
  gkehub/v1/gkehub-gen.go
  gkehub/v1alpha/gkehub-api.json
  gkehub/v1alpha/gkehub-gen.go
  gkehub/v1beta/gkehub-api.json
  gkehub/v1beta/gkehub-gen.go
  gkeonprem/v1/gkeonprem-api.json
  gkeonprem/v1/gkeonprem-gen.go
  redis/v1/redis-api.json
  redis/v1/redis-gen.go
  redis/v1beta1/redis-api.json
  redis/v1beta1/redis-gen.go
  tpu/v2alpha1/tpu-api.json
  tpu/v2alpha1/tpu-gen.go
Labels: automerge: exact

#2261 feat(all): auto-regenerate discovery clients
  batch/v1/batch-api.json
  batch/v1/batch-gen.go
Labels: automerge: exact

#2262 feat(all): auto-regenerate discovery clients
  accessapproval/v1/accessapproval-api.json
  accessapproval/v1/accessapproval-gen.go
  admob/v1beta/admob-api.json
  admob/v1beta/admob-gen.go
  analyticsadmin/v1alpha/analyticsadmin-api.json
  analyticsadmin/v1alpha/analyticsadmin-gen.go
  androiddeviceprovisioning/v1/androiddeviceprovisioning-api.json
  androiddeviceprovisioning/v1/androiddeviceprovisioning-gen.go
  androidpublisher/v3/androidpublisher-api.json
  androidpublisher/v3/androidpublisher-gen.go
  api-list.json
  assuredworkloads/v1/assuredworkloads-api.json
  assuredworkloads/v1/assuredworkloads-gen.go
  assuredworkloads/v1beta1/assuredworkloads-api.json
  assuredworkloads/v1beta1/assuredworkloads-gen.go
  displayvideo/v1/displayvideo-api.json
  displayvideo/v1/displayvideo-gen.go
  displayvideo/v2/displayvideo-api.json
  displayvideo/v2/displayvideo-gen.go
  displayvideo/v3/displayvideo-api.json
  displayvideo/v3/displayvideo-gen.go
  looker/v1/looker-api.json
  looker/v1/looker-gen.go
  paymentsresellersubscription/v1/paymentsresellersubscription-api.json
  paymentsresellersubscription/v1/paymentsresellersubscription-gen.go
  places/v1/places-api.json
  places/v1/places-gen.go
  sasportal/v1alpha1/sasportal-api.json
  sasportal/v1alpha1/sasportal-gen.go
Labels: automerge: exact

#2265 feat(all): auto-regenerate discovery clients
  admin/directory/v1/admin-api.json
  admin/directory/v1/admin-gen.go
  alloydb/v1alpha/alloydb-api.json
  alloydb/v1alpha/alloydb-gen.go
  alloydb/v1beta/alloydb-api.json
  alloydb/v1beta/alloydb-gen.go
  androidpublisher/v3/androidpublisher-api.json
  androidpublisher/v3/androidpublisher-gen.go
  cloudasset/v1/cloudasset-api.json
  cloudasset/v1/cloudasset-gen.go
  cloudbuild/v2/cloudbuild-api.json
  cloudbuild/v2/cloudbuild-gen.go
  clouddeploy/v1/clouddeploy-api.json
  clouddeploy/v1/clouddeploy-gen.go
  connectors/v1/connectors-api.json
  connectors/v1/connectors-gen.go
  container/v1/container-api.json
  container/v1/container-gen.go
  dataform/v1beta1/dataform-api.json
  dataform/v1beta1/dataform-gen.go
  datamigration/v1/datamigration-api.json
  datamigration/v1/datamigration-gen.go
  dataplex/v1/dataplex-api.json
  dataplex/v1/dataplex-gen.go
  dataproc/v1/dataproc-api.json
  dataproc/v1/dataproc-gen.go
  gkebackup/v1/gkebackup-api.json
  gkebackup/v1/gkebackup-gen.go
  gkeonprem/v1/gkeonprem-api.json
  gkeonprem/v1/gkeonprem-gen.go
  metastore/v1/metastore-api.json
  metastore/v1/metastore-gen.go
  metastore/v1alpha/metastore-api.json
  metastore/v1alpha/metastore-gen.go
  metastore/v1beta/metastore-api.json
  metastore/v1beta/metastore-gen.go
  migrationcenter/v1alpha1/migrationcenter-api.json
  migrationcenter/v1alpha1/migrationcenter-gen.go
  networkmanagement/v1/networkmanagement-api.json
  networkmanagement/v1/networkmanagement-gen.go
  networkmanagement/v1beta1/networkmanagement-api.json
  networkmanagement/v1beta1/networkmanagement-gen.go
  ondemandscanning/v1/ondemandscanning-api.json
  ondemandscanning/v1/ondemandscanning-gen.go
  ondemandscanning/v1beta1/ondemandscanning-api.json
  ondemandscanning/v1beta1/ondemandscanning-gen.go
  recaptchaenterprise/v1/recaptchaenterprise-api.json
  recaptchaenterprise/v1/recaptchaenterprise-gen.go
  recommender/v1/recommender-api.json
  recommender/v1/recommender-gen.go
  retail/v2/retail-api.json
  retail/v2/retail-gen.go
  retail/v2alpha/retail-api.json
  retail/v2alpha/retail-gen.go
  retail/v2beta/retail-api.json
  retail/v2beta/retail-gen.go
  workstations/v1/workstations-api.json
  workstations/v1/workstations-gen.go
  workstations/v1beta/workstations-api.json
  workstations/v1beta/workstations-gen.go
Labels: automerge: exact

#2266 feat(all): auto-regenerate discovery clients
  chat/v1/chat-api.json
  chat/v1/chat-gen.go
  cloudbilling/v1/cloudbilling-api.json
  cloudbilling/v1/cloudbilling-gen.go
  cloudbilling/v1beta/cloudbilling-api.json
  cloudbilling/v1beta/cloudbilling-gen.go
  container/v1beta1/container-api.json
  container/v1beta1/container-gen.go
  dataflow/v1b3/dataflow-api.json
  dataflow/v1b3/dataflow-gen.go
  documentai/v1/documentai-api.json
  documentai/v1/documentai-gen.go
  documentai/v1beta2/documentai-api.json
  documentai/v1beta2/documentai-gen.go
  documentai/v1beta3/documentai-api.json
  documentai/v1beta3/documentai-gen.go
  logging/v2/logging-api.json
  logging/v2/logging-gen.go
  monitoring/v3/monitoring-api.json
  monitoring/v3/monitoring-gen.go
  run/v2/run-api.json
  run/v2/run-gen.go
Labels: automerge: exact

#2269 feat(all): auto-regenerate discovery clients
  vpcaccess/v1/vpcaccess-api.json
  vpcaccess/v1/vpcaccess-gen.go
  vpcaccess/v1beta1/vpcaccess-api.json
  vpcaccess/v1beta1/vpcaccess-gen.go
Labels: automerge: exact

#2270 feat(all): auto-regenerate discovery clients
  alloydb/v1/alloydb-api.json
  alloydb/v1/alloydb-gen.go
Labels: automerge: exact

#2271 feat(all): auto-regenerate discovery clients
  api-list.json
  bigquerydatapolicy/v1/bigquerydatapolicy-api.json
  bigquerydatapolicy/v1/bigquerydatapolicy-gen.go
  chat/v1/chat-api.json
  chat/v1/chat-gen.go
  go.work.sum
  places/v1/places-api.json
  places/v1/places-gen.go
  playintegrity/v1/playintegrity-api.json
  playintegrity/v1/playintegrity-gen.go
  servicenetworking/v1/servicenetworking-api.json
  servicenetworking/v1/servicenetworking-gen.go
  servicenetworking/v1beta/servicenetworking-api.json
  servicenetworking/v1beta/servicenetworking-gen.go
Labels: automerge, automerge: exact

#2279 feat(all): auto-regenerate discovery clients
  chat/v1/chat-api.json
  chat/v1/chat-gen.go
  chromepolicy/v1/chromepolicy-api.json
  chromepolicy/v1/chromepolicy-gen.go
  networksecurity/v1beta1/networksecurity-api.json
  networksecurity/v1beta1/networksecurity-gen.go
  paymentsresellersubscription/v1/paymentsresellersubscription-api.json
  paymentsresellersubscription/v1/paymentsresellersubscription-gen.go
  smartdevicemanagement/v1/smartdevicemanagement-api.json
  smartdevicemanagement/v1/smartdevicemanagement-gen.go
Labels: automerge: exact

#2280 feat(all): auto-regenerate discovery clients
  androidmanagement/v1/androidmanagement-api.json
  androidmanagement/v1/androidmanagement-gen.go
  api-list.json
  authorizedbuyersmarketplace/v1/authorizedbuyersmarketplace-api.json
  authorizedbuyersmarketplace/v1/authorizedbuyersmarketplace-gen.go
  classroom/v1/classroom-api.json
  classroom/v1/classroom-gen.go
  cloudbuild/v1/cloudbuild-api.json
  cloudbuild/v1/cloudbuild-gen.go
  cloudbuild/v2/cloudbuild-api.json
  cloudbuild/v2/cloudbuild-gen.go
  content/v2.1/content-api.json
  content/v2.1/content-gen.go
  dialogflow/v2/dialogflow-api.json
  dialogflow/v2/dialogflow-gen.go
  dialogflow/v2beta1/dialogflow-api.json
  dialogflow/v2beta1/dialogflow-gen.go
  dialogflow/v3/dialogflow-api.json
  dialogflow/v3/dialogflow-gen.go
  dialogflow/v3beta1/dialogflow-api.json
  dialogflow/v3beta1/dialogflow-gen.go
  dlp/v2/dlp-api.json
  dlp/v2/dlp-gen.go
  serviceconsumermanagement/v1beta1/serviceconsumermanagement-api.json
  serviceconsumermanagement/v1beta1/serviceconsumermanagement-gen.go
  walletobjects/v1/walletobjects-api.json
  walletobjects/v1/walletobjects-gen.go
Labels: automerge: exact

#2264 feat: expose experimental universe-related options
  internal/settings.go
  option/internaloption/internaloption.go
  option/internaloption/internaloption_test.go
  option/option.go
  option/option_test.go
Labels: automerge
