Repository googleapis/google-api-go-client, pull requests merged in 2023-09, with the labels that each got.

#2146 chore: mark dir as safe for discogen
  internal/kokoro/discogen.sh
Labels: automerge

#2147 chore: add global flag to previous commit as this is not the git root
  internal/kokoro/discogen.sh
Labels: automerge

#2148 feat(all): auto-regenerate discovery clients
  checks/v1alpha/checks-api.json
  checks/v1alpha/checks-gen.go
  firebase/v1beta1/firebase-api.json
  firebase/v1beta1/firebase-gen.go
  gmailpostmastertools/v1/gmailpostmastertools-api.json
  gmailpostmastertools/v1/gmailpostmastertools-gen.go
  gmailpostmastertools/v1beta1/gmailpostmastertools-api.json
  gmailpostmastertools/v1beta1/gmailpostmastertools-gen.go
Labels: automerge, automerge: exact

#2149 feat(all): auto-regenerate discovery clients
  artifactregistry/v1/artifactregistry-api.json
  artifactregistry/v1/artifactregistry-gen.go
  artifactregistry/v1beta2/artifactregistry-api.json
  artifactregistry/v1beta2/artifactregistry-gen.go
  composer/v1/composer-api.json
  composer/v1/composer-gen.go
  datastore/v1/datastore-api.json
  datastore/v1/datastore-gen.go
  datastore/v1beta3/datastore-api.json
  datastore/v1beta3/datastore-gen.go
  domains/v1/domains-api.json
  domains/v1/domains-gen.go
  domains/v1alpha2/domains-api.json
  domains/v1alpha2/domains-gen.go
  domains/v1beta1/domains-api.json
  domains/v1beta1/domains-gen.go
  firestore/v1/firestore-api.json
  firestore/v1/firestore-gen.go
  firestore/v1beta1/firestore-api.json
  firestore/v1beta1/firestore-gen.go
  firestore/v1beta2/firestore-api.json
  firestore/v1beta2/firestore-gen.go
  gkehub/v1/gkehub-api.json
  gkehub/v1/gkehub-gen.go
  gkehub/v1alpha/gkehub-api.json
  gkehub/v1alpha/gkehub-gen.go
  gkehub/v1beta/gkehub-api.json
  gkehub/v1beta/gkehub-gen.go
  networkconnectivity/v1/networkconnectivity-api.json
  networkconnectivity/v1/networkconnectivity-gen.go
  networksecurity/v1beta1/networksecurity-api.json
  networksecurity/v1beta1/networksecurity-gen.go
  tpu/v2alpha1/tpu-api.json
  tpu/v2alpha1/tpu-gen.go
  workloadmanager/v1/workloadmanager-api.json
  workloadmanager/v1/workloadmanager-gen.go
Labels: automerge: exact

#2150 feat(all): auto-regenerate discovery clients
  beyondcorp/v1/beyondcorp-api.json
  beyondcorp/v1/beyondcorp-gen.go
  beyondcorp/v1alpha/beyondcorp-api.json
  beyondcorp/v1alpha/beyondcorp-gen.go
  workstations/v1/workstations-api.json
  workstations/v1/workstations-gen.go
  workstations/v1beta/workstations-api.json
  workstations/v1beta/workstations-gen.go
Labels: automerge: exact

#2152 feat(all): auto-regenerate discovery clients
  redis/v1beta1/redis-api.json
  redis/v1beta1/redis-gen.go
Labels: automerge: exact

#2154 chore(deps): temporarily ignore grpc dep
  .github/renovate.json
Labels: automerge

#2155 feat(all): auto-regenerate discovery clients
  api-list.json
  cloudchannel/v1/cloudchannel-api.json
  cloudchannel/v1/cloudchannel-gen.go
  displayvideo/v1/displayvideo-api.json
  displayvideo/v1/displayvideo-gen.go
  displayvideo/v2/displayvideo-api.json
  displayvideo/v2/displayvideo-gen.go
  firebasehosting/v1/firebasehosting-api.json
  firebasehosting/v1/firebasehosting-gen.go
  firebasehosting/v1beta1/firebasehosting-api.json
  firebasehosting/v1beta1/firebasehosting-gen.go
  healthcare/v1/healthcare-api.json
  healthcare/v1/healthcare-gen.go
  healthcare/v1beta1/healthcare-api.json
  healthcare/v1beta1/healthcare-gen.go
  memcache/v1/memcache-api.json
  memcache/v1/memcache-gen.go
  memcache/v1beta2/memcache-api.json
  memcache/v1beta2/memcache-gen.go
  playintegrity/v1/playintegrity-api.json
  playintegrity/v1/playintegrity-gen.go
  recommender/v1/recommender-api.json
  recommender/v1/recommender-gen.go
  recommender/v1beta1/recommender-api.json
  recommender/v1beta1/recommender-gen.go
  securitycenter/v1/securitycenter-api.json
  securitycenter/v1/securitycenter-gen.go
  securitycenter/v1beta1/securitycenter-api.json
  securitycenter/v1beta1/securitycenter-gen.go
  securitycenter/v1beta2/securitycenter-api.json
  securitycenter/v1beta2/securitycenter-gen.go
  storage/v1/storage-api.json
  storage/v1/storage-gen.go
  vision/v1/vision-api.json
  vision/v1/vision-gen.go
  vision/v1p1beta1/vision-api.json
  vision/v1p1beta1/vision-gen.go
  vision/v1p2beta1/vision-api.json
  vision/v1p2beta1/vision-gen.go
Labels: automerge: exact

#2158 fix(transport): remove conditional App Engine gen 1 Go hooks
  go.mod
  transport/grpc/dial.go
  transport/grpc/dial_appengine.go
  transport/grpc/dial_test.go
  transport/http/dial.go
  transport/http/dial_appengine.go
Labels: automerge

#2160 feat(all): auto-regenerate discovery clients
  advisorynotifications/v1/advisorynotifications-api.json
  advisorynotifications/v1/advisorynotifications-gen.go
  analyticshub/v1/analyticshub-api.json
  analyticshub/v1/analyticshub-gen.go
  blockchainnodeengine/v1/blockchainnodeengine-api.json
  blockchainnodeengine/v1/blockchainnodeengine-gen.go
  checks/v1alpha/checks-api.json
  checks/v1alpha/checks-gen.go
  cloudfunctions/v2/cloudfunctions-api.json
  cloudfunctions/v2/cloudfunctions-gen.go
  cloudfunctions/v2alpha/cloudfunctions-api.json
  cloudfunctions/v2alpha/cloudfunctions-gen.go
  cloudfunctions/v2beta/cloudfunctions-api.json
  cloudfunctions/v2beta/cloudfunctions-gen.go
  contactcenterinsights/v1/contactcenterinsights-api.json
  contactcenterinsights/v1/contactcenterinsights-gen.go
  gmail/v1/gmail-api.json
  gmail/v1/gmail-gen.go
  places/v1/places-api.json
  places/v1/places-gen.go
  run/v2/run-api.json
  run/v2/run-gen.go
Labels: automerge: exact

#2136 feat(idtoken): add ParsePayload returning unvalidated token payload
  idtoken/validate.go
  idtoken/validate_test.go
Labels: automerge

#2161 feat(all): auto-regenerate discovery clients
  appengine/v1/appengine-api.json
  appengine/v1/appengine-gen.go
  appengine/v1beta/appengine-api.json
  appengine/v1beta/appengine-gen.go
  chromemanagement/v1/chromemanagement-api.json
  chromemanagement/v1/chromemanagement-gen.go
  displayvideo/v1/displayvideo-api.json
  displayvideo/v1/displayvideo-gen.go
  displayvideo/v2/displayvideo-api.json
  displayvideo/v2/displayvideo-gen.go
  firebasehosting/v1/firebasehosting-api.json
  firebasehosting/v1/firebasehosting-gen.go
  firebasehosting/v1beta1/firebasehosting-api.json
  firebasehosting/v1beta1/firebasehosting-gen.go
  monitoring/v1/monitoring-api.json
  monitoring/v1/monitoring-gen.go
  mybusinessverifications/v1/mybusinessverifications-api.json
  mybusinessverifications/v1/mybusinessverifications-gen.go
  paymentsresellersubscription/v1/paymentsresellersubscription-api.json
  paymentsresellersubscription/v1/paymentsresellersubscription-gen.go
  run/v1/run-api.json
  run/v1/run-gen.go
  serviceusage/v1/serviceusage-api.json
  serviceusage/v1/serviceusage-gen.go
  serviceusage/v1beta1/serviceusage-api.json
  serviceusage/v1beta1/serviceusage-gen.go
Labels: automerge: exact

#2163 feat(internal): add some feature flags for new auth libs
  internal/settings.go
  option/internaloption/internaloption.go
Labels: automerge

#2165 feat(all): auto-regenerate discovery clients
  artifactregistry/v1/artifactregistry-api.json
  artifactregistry/v1/artifactregistry-gen.go
  artifactregistry/v1beta1/artifactregistry-api.json
  artifactregistry/v1beta1/artifactregistry-gen.go
  artifactregistry/v1beta2/artifactregistry-api.json
  artifactregistry/v1beta2/artifactregistry-gen.go
  batch/v1/batch-api.json
  batch/v1/batch-gen.go
  certificatemanager/v1/certificatemanager-api.json
  certificatemanager/v1/certificatemanager-gen.go
  cloudtasks/v2/cloudtasks-api.json
  cloudtasks/v2/cloudtasks-gen.go
  cloudtasks/v2beta2/cloudtasks-api.json
  cloudtasks/v2beta2/cloudtasks-gen.go
  cloudtasks/v2beta3/cloudtasks-api.json
  cloudtasks/v2beta3/cloudtasks-gen.go
  connectors/v1/connectors-api.json
  connectors/v1/connectors-gen.go
  connectors/v2/connectors-api.json
  connectors/v2/connectors-gen.go
  dataform/v1beta1/dataform-api.json
  networkconnectivity/v1/networkconnectivity-api.json
  networkconnectivity/v1/networkconnectivity-gen.go
  transcoder/v1/transcoder-api.json
  transcoder/v1/transcoder-gen.go
  workflows/v1/workflows-api.json
  workflows/v1/workflows-gen.go
Labels: automerge: exact

#2166 feat(all): auto-regenerate discovery clients
  beyondcorp/v1/beyondcorp-api.json
  beyondcorp/v1/beyondcorp-gen.go
  notebooks/v1/notebooks-api.json
  notebooks/v1/notebooks-gen.go
  notebooks/v2/notebooks-api.json
  notebooks/v2/notebooks-gen.go
Labels: automerge: exact

#2168 feat(all): auto-regenerate discovery clients
  datamigration/v1/datamigration-api.json
  datamigration/v1/datamigration-gen.go
  gkeonprem/v1/gkeonprem-api.json
  gkeonprem/v1/gkeonprem-gen.go
  spanner/v1/spanner-api.json
  spanner/v1/spanner-gen.go
  storage/v1/storage-api.json
  storage/v1/storage-gen.go
Labels: automerge: exact

#2164 feat(all): use updated mtls config endpoint
  internal/s2a.go
Labels: automerge

#2179 feat(all): auto-regenerate discovery clients
  assuredworkloads/v1/assuredworkloads-api.json
  assuredworkloads/v1/assuredworkloads-gen.go
  assuredworkloads/v1beta1/assuredworkloads-api.json
  assuredworkloads/v1beta1/assuredworkloads-gen.go
  batch/v1/batch-api.json
  batch/v1/batch-gen.go
  containeranalysis/v1/containeranalysis-api.json
  containeranalysis/v1/containeranalysis-gen.go
  containeranalysis/v1alpha1/containeranalysis-api.json
  containeranalysis/v1alpha1/containeranalysis-gen.go
  containeranalysis/v1beta1/containeranalysis-api.json
  containeranalysis/v1beta1/containeranalysis-gen.go
  datamigration/v1/datamigration-api.json
  datamigration/v1/datamigration-gen.go
  gkehub/v1/gkehub-api.json
  gkehub/v1/gkehub-gen.go
  gkehub/v1alpha/gkehub-api.json
  gkehub/v1alpha/gkehub-gen.go
  gkehub/v1beta/gkehub-api.json
  gkehub/v1beta/gkehub-gen.go
  prod_tt_sasportal/v1alpha1/prod_tt_sasportal-api.json
  prod_tt_sasportal/v1alpha1/prod_tt_sasportal-gen.go
  workflows/v1/workflows-api.json
  workflows/v1/workflows-gen.go
Labels: automerge: exact

#2180 feat(all): auto-regenerate discovery clients
  eventarc/v1/eventarc-api.json
  eventarc/v1/eventarc-gen.go
  gkeonprem/v1/gkeonprem-api.json
  gkeonprem/v1/gkeonprem-gen.go
  networksecurity/v1beta1/networksecurity-api.json
  networksecurity/v1beta1/networksecurity-gen.go
Labels: automerge: exact

#2182 feat(all): auto-regenerate discovery clients
  api-list.json
  deploymentmanager/v2/deploymentmanager-api.json
  deploymentmanager/v2/deploymentmanager-gen.go
Labels: automerge: exact

#2183 chore: unfreeze grpc
  .github/renovate.json
Labels: automerge

#2185 chore: give admins ownership of everything
  .github/CODEOWNERS
Labels: automerge
