Repository googleapis/google-api-go-client, pull requests merged in 2024-01, with the labels that each got.

#2328 feat(all): auto-regenerate discovery clients
  oslogin/v1/oslogin-gen.go
  oslogin/v1alpha/oslogin-gen.go
  oslogin/v1beta/oslogin-gen.go
Labels: automerge: exact

#2331 feat(all): auto-regenerate discovery clients
  admin/directory/v1/admin-api.json
  admin/directory/v1/admin-gen.go
  calendar/v3/calendar-gen.go
  chromeuxreport/v1/chromeuxreport-api.json
  chromeuxreport/v1/chromeuxreport-gen.go
  cloudidentity/v1beta1/cloudidentity-api.json
  cloudidentity/v1beta1/cloudidentity-gen.go
  contactcenterinsights/v1/contactcenterinsights-api.json
  contactcenterinsights/v1/contactcenterinsights-gen.go
  serviceconsumermanagement/v1beta1/serviceconsumermanagement-api.json
  serviceconsumermanagement/v1beta1/serviceconsumermanagement-gen.go
  spanner/v1/spanner-gen.go
Labels: automerge: exact

#2336 feat(all): auto-regenerate discovery clients
  accesscontextmanager/v1/accesscontextmanager-api.json
  accesscontextmanager/v1/accesscontextmanager-gen.go
  cloudtrace/v1/cloudtrace-api.json
  cloudtrace/v1/cloudtrace-gen.go
  datacatalog/v1beta1/datacatalog-api.json
  datacatalog/v1beta1/datacatalog-gen.go
  servicemanagement/v1/servicemanagement-api.json
  servicemanagement/v1/servicemanagement-gen.go
  storage/v1/storage-api.json
  storage/v1/storage-gen.go
Labels: automerge: exact

#2337 feat(all): auto-regenerate discovery clients
  artifactregistry/v1/artifactregistry-api.json
  artifactregistry/v1/artifactregistry-gen.go
  artifactregistry/v1beta1/artifactregistry-api.json
  artifactregistry/v1beta1/artifactregistry-gen.go
  artifactregistry/v1beta2/artifactregistry-api.json
  artifactregistry/v1beta2/artifactregistry-gen.go
  backupdr/v1/backupdr-api.json
  backupdr/v1/backupdr-gen.go
  batch/v1/batch-api.json
  batch/v1/batch-gen.go
  cloudprofiler/v2/cloudprofiler-api.json
  cloudprofiler/v2/cloudprofiler-gen.go
  connectors/v1/connectors-api.json
  connectors/v1/connectors-gen.go
  dataplex/v1/dataplex-api.json
  dataplex/v1/dataplex-gen.go
  eventarc/v1/eventarc-api.json
  eventarc/v1/eventarc-gen.go
  eventarc/v1beta1/eventarc-api.json
  eventarc/v1beta1/eventarc-gen.go
  firestore/v1/firestore-gen.go
  firestore/v1beta1/firestore-gen.go
  ml/v1/ml-gen.go
  notebooks/v1/notebooks-gen.go
  notebooks/v2/notebooks-gen.go
  sqladmin/v1/sqladmin-api.json
  sqladmin/v1/sqladmin-gen.go
  sqladmin/v1beta4/sqladmin-api.json
  sqladmin/v1beta4/sqladmin-gen.go
Labels: automerge: exact

#2339 feat(all): auto-regenerate discovery clients
  dataproc/v1/dataproc-api.json
  dataproc/v1/dataproc-gen.go
Labels: automerge: exact

#2342 test: fix overflow
  iterator/iterator_test.go
Labels: kokoro:force-run, automerge: exact

#2345 feat(all): auto-regenerate discovery clients
  androidpublisher/v3/androidpublisher-api.json
  androidpublisher/v3/androidpublisher-gen.go
  apigee/v1/apigee-api.json
  apigee/v1/apigee-gen.go
  chat/v1/chat-api.json
  chat/v1/chat-gen.go
  content/v2.1/content-api.json
  content/v2.1/content-gen.go
  dataproc/v1/dataproc-gen.go
  displayvideo/v2/displayvideo-api.json
  displayvideo/v2/displayvideo-gen.go
  displayvideo/v3/displayvideo-api.json
  displayvideo/v3/displayvideo-gen.go
  healthcare/v1/healthcare-api.json
  healthcare/v1/healthcare-gen.go
  healthcare/v1beta1/healthcare-api.json
  healthcare/v1beta1/healthcare-gen.go
  iam/v1/iam-api.json
  iam/v1/iam-gen.go
  iam/v2/iam-api.json
  iam/v2/iam-gen.go
  iam/v2beta/iam-api.json
  iam/v2beta/iam-gen.go
  prod_tt_sasportal/v1alpha1/prod_tt_sasportal-api.json
  prod_tt_sasportal/v1alpha1/prod_tt_sasportal-gen.go
  recommender/v1beta1/recommender-gen.go
  sasportal/v1alpha1/sasportal-api.json
  sasportal/v1alpha1/sasportal-gen.go
  securitycenter/v1/securitycenter-gen.go
  securitycenter/v1beta1/securitycenter-gen.go
  securitycenter/v1beta2/securitycenter-gen.go
Labels: automerge: exact

#2348 feat(all): auto-regenerate discovery clients
  analyticshub/v1/analyticshub-api.json
  analyticshub/v1/analyticshub-gen.go
  analyticshub/v1beta1/analyticshub-api.json
  analyticshub/v1beta1/analyticshub-gen.go
  bigquerydatapolicy/v1/bigquerydatapolicy-api.json
  bigquerydatapolicy/v1/bigquerydatapolicy-gen.go
  bigtableadmin/v2/bigtableadmin-api.json
  bigtableadmin/v2/bigtableadmin-gen.go
  chromepolicy/v1/chromepolicy-api.json
  chromepolicy/v1/chromepolicy-gen.go
  dlp/v2/dlp-api.json
  dlp/v2/dlp-gen.go
  drive/v2/drive-api.json
  drive/v2/drive-gen.go
  drive/v3/drive-api.json
  drive/v3/drive-gen.go
  logging/v2/logging-api.json
  logging/v2/logging-gen.go
  migrationcenter/v1/migrationcenter-api.json
  migrationcenter/v1/migrationcenter-gen.go
  privateca/v1/privateca-api.json
  privateca/v1/privateca-gen.go
  sasportal/v1alpha1/sasportal-api.json
  sasportal/v1alpha1/sasportal-gen.go
  spanner/v1/spanner-api.json
  spanner/v1/spanner-gen.go
Labels: automerge: exact

#2349 feat(all): auto-regenerate discovery clients
  datamigration/v1/datamigration-api.json
  datamigration/v1/datamigration-gen.go
  domains/v1/domains-api.json
  domains/v1/domains-gen.go
  domains/v1beta1/domains-api.json
  domains/v1beta1/domains-gen.go
  memcache/v1/memcache-api.json
  memcache/v1/memcache-gen.go
  memcache/v1beta2/memcache-api.json
  memcache/v1beta2/memcache-gen.go
  networkmanagement/v1/networkmanagement-api.json
  networkmanagement/v1/networkmanagement-gen.go
  networkmanagement/v1beta1/networkmanagement-api.json
  networkmanagement/v1beta1/networkmanagement-gen.go
  vmwareengine/v1/vmwareengine-api.json
  vmwareengine/v1/vmwareengine-gen.go
Labels: automerge: exact

#2352 feat(all): auto-regenerate discovery clients
  api-list.json
  bigqueryconnection/v1/bigqueryconnection-api.json
  bigqueryconnection/v1/bigqueryconnection-gen.go
  dataform/v1beta1/dataform-api.json
  dataform/v1beta1/dataform-gen.go
  looker/v1/looker-api.json
  looker/v1/looker-gen.go
  networksecurity/v1/networksecurity-api.json
  networksecurity/v1/networksecurity-gen.go
  networksecurity/v1beta1/networksecurity-api.json
  networksecurity/v1beta1/networksecurity-gen.go
  networkservices/v1/networkservices-api.json
  networkservices/v1/networkservices-gen.go
  networkservices/v1beta1/networkservices-api.json
  networkservices/v1beta1/networkservices-gen.go
Labels: automerge: exact

#2358 feat(all): auto-regenerate discovery clients
  androidpublisher/v3/androidpublisher-api.json
  androidpublisher/v3/androidpublisher-gen.go
  bigtableadmin/v2/bigtableadmin-api.json
  bigtableadmin/v2/bigtableadmin-gen.go
  calendar/v3/calendar-api.json
  calendar/v3/calendar-gen.go
  cloudresourcemanager/v1/cloudresourcemanager-api.json
  cloudresourcemanager/v1/cloudresourcemanager-gen.go
  cloudresourcemanager/v1beta1/cloudresourcemanager-api.json
  cloudresourcemanager/v1beta1/cloudresourcemanager-gen.go
  cloudresourcemanager/v2/cloudresourcemanager-api.json
  cloudresourcemanager/v2/cloudresourcemanager-gen.go
  cloudresourcemanager/v2beta1/cloudresourcemanager-api.json
  cloudresourcemanager/v2beta1/cloudresourcemanager-gen.go
  cloudresourcemanager/v3/cloudresourcemanager-api.json
  cloudresourcemanager/v3/cloudresourcemanager-gen.go
  contactcenterinsights/v1/contactcenterinsights-api.json
  contactcenterinsights/v1/contactcenterinsights-gen.go
  content/v2.1/content-api.json
  content/v2.1/content-gen.go
  dataflow/v1b3/dataflow-api.json
  dataflow/v1b3/dataflow-gen.go
  securitycenter/v1/securitycenter-api.json
  securitycenter/v1/securitycenter-gen.go
  securitycenter/v1beta1/securitycenter-api.json
  securitycenter/v1beta1/securitycenter-gen.go
  securitycenter/v1beta2/securitycenter-api.json
  securitycenter/v1beta2/securitycenter-gen.go
Labels: automerge: exact

#2361 feat(all): auto-regenerate discovery clients
  api-list.json
  displayvideo/v1/displayvideo-api.json
  displayvideo/v1/displayvideo-gen.go
  displayvideo/v2/displayvideo-api.json
  displayvideo/v2/displayvideo-gen.go
  displayvideo/v3/displayvideo-api.json
  displayvideo/v3/displayvideo-gen.go
  displayvideo/v4/displayvideo-api.json
  displayvideo/v4/displayvideo-gen.go
  logging/v2/logging-api.json
  logging/v2/logging-gen.go
  managedidentities/v1/managedidentities-api.json
  managedidentities/v1/managedidentities-gen.go
  managedidentities/v1alpha1/managedidentities-api.json
  managedidentities/v1alpha1/managedidentities-gen.go
  managedidentities/v1beta1/managedidentities-api.json
  managedidentities/v1beta1/managedidentities-gen.go
  run/v1/run-api.json
  run/v1/run-gen.go
  walletobjects/v1/walletobjects-api.json
  walletobjects/v1/walletobjects-gen.go
Labels: automerge: exact

#2365 feat(all): auto-regenerate discovery clients
  dialogflow/v2beta1/dialogflow-api.json
  dialogflow/v2beta1/dialogflow-gen.go
  dialogflow/v3/dialogflow-api.json
  dialogflow/v3/dialogflow-gen.go
  dialogflow/v3beta1/dialogflow-api.json
  dialogflow/v3beta1/dialogflow-gen.go
  dlp/v2/dlp-api.json
  dlp/v2/dlp-gen.go
Labels: automerge: exact

#2366 feat(all): auto-regenerate discovery clients
  apphub/v1/apphub-api.json
  apphub/v1/apphub-gen.go
  batch/v1/batch-api.json
  batch/v1/batch-gen.go
  connectors/v1/connectors-api.json
  connectors/v1/connectors-gen.go
  dataplex/v1/dataplex-api.json
  dataplex/v1/dataplex-gen.go
  dialogflow/v2/dialogflow-api.json
  dialogflow/v2/dialogflow-gen.go
  firestore/v1/firestore-api.json
  firestore/v1/firestore-gen.go
  firestore/v1beta1/firestore-api.json
  firestore/v1beta1/firestore-gen.go
  gkehub/v1/gkehub-api.json
  gkehub/v1/gkehub-gen.go
  gkehub/v1alpha/gkehub-api.json
  gkehub/v1alpha/gkehub-gen.go
  gkehub/v1alpha2/gkehub-api.json
  gkehub/v1alpha2/gkehub-gen.go
  gkehub/v1beta/gkehub-api.json
  gkehub/v1beta/gkehub-gen.go
  gkehub/v1beta1/gkehub-api.json
  gkehub/v1beta1/gkehub-gen.go
  metastore/v1/metastore-api.json
  metastore/v1/metastore-gen.go
  metastore/v1alpha/metastore-api.json
  metastore/v1alpha/metastore-gen.go
  notebooks/v2/notebooks-api.json
  notebooks/v2/notebooks-gen.go
  redis/v1/redis-api.json
  redis/v1/redis-gen.go
  redis/v1beta1/redis-api.json
  redis/v1beta1/redis-gen.go
  sqladmin/v1/sqladmin-api.json
  sqladmin/v1/sqladmin-gen.go
  sqladmin/v1beta4/sqladmin-api.json
  sqladmin/v1beta4/sqladmin-gen.go
  tpu/v2/tpu-api.json
  tpu/v2/tpu-gen.go
  tpu/v2alpha1/tpu-api.json
  tpu/v2alpha1/tpu-gen.go
  vmwareengine/v1/vmwareengine-api.json
  vmwareengine/v1/vmwareengine-gen.go
  workflows/v1/workflows-api.json
  workflows/v1/workflows-gen.go
Labels: automerge: exact

#2372 feat(all): auto-regenerate discovery clients
  androidmanagement/v1/androidmanagement-api.json
  androidmanagement/v1/androidmanagement-gen.go
  blockchainnodeengine/v1/blockchainnodeengine-api.json
  blockchainnodeengine/v1/blockchainnodeengine-gen.go
  discoveryengine/v1alpha/discoveryengine-api.json
  discoveryengine/v1alpha/discoveryengine-gen.go
  discoveryengine/v1beta/discoveryengine-api.json
  discoveryengine/v1beta/discoveryengine-gen.go
  firebaseappcheck/v1beta/firebaseappcheck-api.json
  firebaseappcheck/v1beta/firebaseappcheck-gen.go
  healthcare/v1/healthcare-api.json
  healthcare/v1/healthcare-gen.go
  healthcare/v1beta1/healthcare-api.json
  healthcare/v1beta1/healthcare-gen.go
  osconfig/v1/osconfig-api.json
  osconfig/v1/osconfig-gen.go
Labels: automerge: exact

#2374 feat(all): auto-regenerate discovery clients
  admin/reports/v1/admin-api.json
  admin/reports/v1/admin-gen.go
  cloudbilling/v1/cloudbilling-api.json
  cloudbilling/v1/cloudbilling-gen.go
  container/v1beta1/container-api.json
  container/v1beta1/container-gen.go
  content/v2.1/content-api.json
  content/v2.1/content-gen.go
  datacatalog/v1/datacatalog-api.json
  datacatalog/v1/datacatalog-gen.go
  datacatalog/v1beta1/datacatalog-api.json
  datacatalog/v1beta1/datacatalog-gen.go
  dns/v1/dns-api.json
  dns/v1/dns-gen.go
  dns/v1beta2/dns-api.json
  dns/v1beta2/dns-gen.go
  iam/v1/iam-api.json
  iam/v1/iam-gen.go
  iap/v1/iap-api.json
  iap/v1/iap-gen.go
  iap/v1beta1/iap-api.json
  iap/v1beta1/iap-gen.go
  retail/v2/retail-api.json
  retail/v2/retail-gen.go
  retail/v2alpha/retail-api.json
  retail/v2alpha/retail-gen.go
  retail/v2beta/retail-api.json
  retail/v2beta/retail-gen.go
  run/v1/run-api.json
  run/v1/run-gen.go
  sourcerepo/v1/sourcerepo-api.json
  sourcerepo/v1/sourcerepo-gen.go
  spanner/v1/spanner-api.json
  spanner/v1/spanner-gen.go
  versionhistory/v1/versionhistory-api.json
  versionhistory/v1/versionhistory-gen.go
  youtube/v3/youtube-api.json
  youtube/v3/youtube-gen.go
Labels: automerge: exact

#2377 feat(all): auto-regenerate discovery clients
  api-list.json
  apphub/v1/apphub-api.json
  apphub/v1/apphub-gen.go
  apphub/v1alpha/apphub-api.json
  apphub/v1alpha/apphub-gen.go
  artifactregistry/v1beta1/artifactregistry-api.json
  artifactregistry/v1beta1/artifactregistry-gen.go
  cloudasset/v1p5beta1/cloudasset-api.json
  cloudasset/v1p5beta1/cloudasset-gen.go
  cloudfunctions/v1/cloudfunctions-api.json
  cloudfunctions/v1/cloudfunctions-gen.go
  cloudfunctions/v2/cloudfunctions-api.json
  cloudfunctions/v2/cloudfunctions-gen.go
  cloudfunctions/v2alpha/cloudfunctions-api.json
  cloudfunctions/v2alpha/cloudfunctions-gen.go
  cloudfunctions/v2beta/cloudfunctions-api.json
  cloudfunctions/v2beta/cloudfunctions-gen.go
  container/v1/container-api.json
  container/v1/container-gen.go
  dialogflow/v2/dialogflow-api.json
  dialogflow/v2/dialogflow-gen.go
  dialogflow/v2beta1/dialogflow-api.json
  dialogflow/v2beta1/dialogflow-gen.go
  dialogflow/v3/dialogflow-api.json
  dialogflow/v3/dialogflow-gen.go
  dialogflow/v3beta1/dialogflow-api.json
  dialogflow/v3beta1/dialogflow-gen.go
  displayvideo/v1/displayvideo-api.json
  displayvideo/v1/displayvideo-gen.go
  displayvideo/v2/displayvideo-api.json
  displayvideo/v2/displayvideo-gen.go
  displayvideo/v3/displayvideo-api.json
  displayvideo/v3/displayvideo-gen.go
  doubleclicksearch/v2/doubleclicksearch-api.json
  doubleclicksearch/v2/doubleclicksearch-gen.go
  drive/v3/drive-api.json
  drive/v3/drive-gen.go
  identitytoolkit/v2/identitytoolkit-api.json
  identitytoolkit/v2/identitytoolkit-gen.go
  monitoring/v1/monitoring-api.json
  monitoring/v1/monitoring-gen.go
  run/v2/run-api.json
  run/v2/run-gen.go
  servicemanagement/v1/servicemanagement-api.json
  servicemanagement/v1/servicemanagement-gen.go
  vmmigration/v1/vmmigration-api.json
  vmmigration/v1/vmmigration-gen.go
  vmmigration/v1alpha1/vmmigration-api.json
  vmmigration/v1alpha1/vmmigration-gen.go
  workspaceevents/v1/workspaceevents-api.json
  workspaceevents/v1/workspaceevents-gen.go
Labels: automerge: exact

#2376 fix(transport): relax universe checks
  transport/grpc/dial.go
  transport/http/dial.go
  transport/http/dial_test.go
Labels: automerge

#2386 feat(all): auto-regenerate discovery clients
  discoveryengine/v1alpha/discoveryengine-api.json
  discoveryengine/v1alpha/discoveryengine-gen.go
  discoveryengine/v1beta/discoveryengine-api.json
  discoveryengine/v1beta/discoveryengine-gen.go
  retail/v2/retail-api.json
  retail/v2/retail-gen.go
  retail/v2alpha/retail-api.json
  retail/v2alpha/retail-gen.go
  retail/v2beta/retail-api.json
  retail/v2beta/retail-gen.go
  storagetransfer/v1/storagetransfer-api.json
  storagetransfer/v1/storagetransfer-gen.go
  translate/v3/translate-api.json
  translate/v3/translate-gen.go
Labels: automerge: exact

#2385 fix(transport): skip s2a for now if service has direct path enabled
  internal/cba.go
  internal/cba_test.go
Labels: automerge

#2383 fix(gen): reject repeated object query params
  google-api-go-generator/gen.go
  google-api-go-generator/gen_test.go
  google-api-go-generator/testdata/repeated_any_query_error.json
  google-api-go-generator/testdata/repeated_any_query_error.want
Labels: automerge

#2388 feat(all): auto-regenerate discovery clients
  accesscontextmanager/v1/accesscontextmanager-api.json
  accesscontextmanager/v1/accesscontextmanager-gen.go
  alertcenter/v1beta1/alertcenter-api.json
  alertcenter/v1beta1/alertcenter-gen.go
  cloudresourcemanager/v1/cloudresourcemanager-api.json
  cloudresourcemanager/v1/cloudresourcemanager-gen.go
  cloudresourcemanager/v1beta1/cloudresourcemanager-api.json
  cloudresourcemanager/v1beta1/cloudresourcemanager-gen.go
  cloudresourcemanager/v2/cloudresourcemanager-api.json
  cloudresourcemanager/v2/cloudresourcemanager-gen.go
  cloudresourcemanager/v2beta1/cloudresourcemanager-api.json
  cloudresourcemanager/v2beta1/cloudresourcemanager-gen.go
  cloudresourcemanager/v3/cloudresourcemanager-api.json
  cloudresourcemanager/v3/cloudresourcemanager-gen.go
  cloudsupport/v2beta/cloudsupport-api.json
  cloudsupport/v2beta/cloudsupport-gen.go
  dataform/v1beta1/dataform-api.json
  dataform/v1beta1/dataform-gen.go
  metastore/v1/metastore-api.json
  metastore/v1/metastore-gen.go
  metastore/v1alpha/metastore-api.json
  metastore/v1alpha/metastore-gen.go
  metastore/v1beta/metastore-api.json
  metastore/v1beta/metastore-gen.go
  pubsub/v1/pubsub-api.json
  pubsub/v1/pubsub-gen.go
  pubsub/v1beta2/pubsub-api.json
  pubsub/v1beta2/pubsub-gen.go
  secretmanager/v1/secretmanager-api.json
  secretmanager/v1/secretmanager-gen.go
  secretmanager/v1beta1/secretmanager-api.json
  secretmanager/v1beta1/secretmanager-gen.go
  sqladmin/v1/sqladmin-api.json
  sqladmin/v1/sqladmin-gen.go
  sqladmin/v1beta4/sqladmin-api.json
  sqladmin/v1beta4/sqladmin-gen.go
  workloadmanager/v1/workloadmanager-api.json
  workloadmanager/v1/workloadmanager-gen.go
Labels: automerge: exact
