Repository googleapis/google-api-go-client, pull requests merged in 2024-06, with the labels that each got.

#2622 feat(all): auto-regenerate discovery clients
  androidmanagement/v1/androidmanagement-api.json
  androidmanagement/v1/androidmanagement-gen.go
  artifactregistry/v1/artifactregistry-api.json
  artifactregistry/v1/artifactregistry-gen.go
  artifactregistry/v1beta1/artifactregistry-api.json
  artifactregistry/v1beta1/artifactregistry-gen.go
  artifactregistry/v1beta2/artifactregistry-api.json
  artifactregistry/v1beta2/artifactregistry-gen.go
  chromemanagement/v1/chromemanagement-api.json
  chromemanagement/v1/chromemanagement-gen.go
  cloudsearch/v1/cloudsearch-api.json
  cloudsearch/v1/cloudsearch-gen.go
  documentai/v1/documentai-api.json
  documentai/v1/documentai-gen.go
  documentai/v1beta2/documentai-api.json
  documentai/v1beta2/documentai-gen.go
  documentai/v1beta3/documentai-api.json
  documentai/v1beta3/documentai-gen.go
  fcmdata/v1beta1/fcmdata-api.json
  fcmdata/v1beta1/fcmdata-gen.go
  policyanalyzer/v1/policyanalyzer-api.json
  policyanalyzer/v1/policyanalyzer-gen.go
  policyanalyzer/v1beta1/policyanalyzer-api.json
  policyanalyzer/v1beta1/policyanalyzer-gen.go
  redis/v1/redis-api.json
  redis/v1/redis-gen.go
  redis/v1beta1/redis-api.json
  redis/v1beta1/redis-gen.go
  resourcesettings/v1/resourcesettings-api.json
  serviceconsumermanagement/v1/serviceconsumermanagement-api.json
  serviceconsumermanagement/v1/serviceconsumermanagement-gen.go
  serviceconsumermanagement/v1beta1/serviceconsumermanagement-api.json
  serviceconsumermanagement/v1beta1/serviceconsumermanagement-gen.go
  serviceusage/v1/serviceusage-api.json
  serviceusage/v1/serviceusage-gen.go
  serviceusage/v1beta1/serviceusage-api.json
  serviceusage/v1beta1/serviceusage-gen.go
  sqladmin/v1/sqladmin-api.json
  sqladmin/v1/sqladmin-gen.go
  sqladmin/v1beta4/sqladmin-api.json
  sqladmin/v1beta4/sqladmin-gen.go
Labels: automerge: exact

#2621 chore: bump auth dep
  go.work.sum
Labels: automerge

#2627 feat: regen cloudcommerceprocurement v1 from updated discovery file
  cloudcommerceprocurement/v1/cloudcommerceprocurement-api.json
  cloudcommerceprocurement/v1/cloudcommerceprocurement-gen.go
Labels: automerge: exact

#2631 chore: remove some nil clients
  corp_autopush_learningstate/v1/corp_autopush_learningstate-api.json
  corp_autopush_learningstate/v1/corp_autopush_learningstate-gen.go
  corp_spatialanalytics/v1/corp_spatialanalytics-api.json
  corp_spatialanalytics/v1/corp_spatialanalytics-gen.go
  go.work.sum
Labels: automerge

#2632 feat: support structpb.Struct as req/resp
  go.work.sum
  google-api-go-generator/gen.go
  google-api-go-generator/gen_test.go
  google-api-go-generator/testdata/mapprotostruct.json
  google-api-go-generator/testdata/mapprotostruct.want
Labels: automerge

#2610 fix(cba): Update credsNewAuth to support oauth2 over mTLS
  internal/creds.go
  transport/grpc/dial.go
  transport/http/dial.go
Labels: automerge

#2624 feat(all): auto-regenerate discovery clients
  api-list.json
  assuredworkloads/v1/assuredworkloads-api.json
  assuredworkloads/v1/assuredworkloads-gen.go
  assuredworkloads/v1beta1/assuredworkloads-api.json
  assuredworkloads/v1beta1/assuredworkloads-gen.go
  cloudbilling/v1beta/cloudbilling-api.json
  dialogflow/v2/dialogflow-api.json
  dialogflow/v2/dialogflow-gen.go
  dialogflow/v3/dialogflow-api.json
  dialogflow/v3/dialogflow-gen.go
  discoveryengine/v1/discoveryengine-api.json
  discoveryengine/v1/discoveryengine-gen.go
  discoveryengine/v1alpha/discoveryengine-api.json
  discoveryengine/v1alpha/discoveryengine-gen.go
  discoveryengine/v1beta/discoveryengine-api.json
  discoveryengine/v1beta/discoveryengine-gen.go
  firebaseml/v2beta/firebaseml-api.json
  firebaseml/v2beta/firebaseml-gen.go
  games/v1/games-api.json
  games/v1/games-gen.go
  iam/v1/iam-api.json
  iam/v1/iam-gen.go
  iam/v2/iam-api.json
  iam/v2/iam-gen.go
  iam/v2beta/iam-api.json
  iam/v2beta/iam-gen.go
Labels: automerge, automerge: exact

#2634 fix(internal/gensupport): update shouldRetry for GCS uploads
  internal/gensupport/retry.go
  internal/gensupport/retry_test.go
  internal/gensupport/retryable_linux.go
Labels: api: storage

#2638 feat(all): auto-regenerate discovery clients
  api-list.json
  bigtableadmin/v2/bigtableadmin-api.json
  bigtableadmin/v2/bigtableadmin-gen.go
  binaryauthorization/v1/binaryauthorization-api.json
  binaryauthorization/v1/binaryauthorization-gen.go
  contactcenterinsights/v1/contactcenterinsights-api.json
  contactcenterinsights/v1/contactcenterinsights-gen.go
  discoveryengine/v1/discoveryengine-api.json
  discoveryengine/v1/discoveryengine-gen.go
  discoveryengine/v1alpha/discoveryengine-api.json
  discoveryengine/v1alpha/discoveryengine-gen.go
  discoveryengine/v1beta/discoveryengine-api.json
  discoveryengine/v1beta/discoveryengine-gen.go
  displayvideo/v3/displayvideo-api.json
  displayvideo/v3/displayvideo-gen.go
  dlp/v2/dlp-api.json
  dlp/v2/dlp-gen.go
  firestore/v1/firestore-api.json
  firestore/v1/firestore-gen.go
  merchantapi/accounts_v1beta/merchantapi-api.json
  merchantapi/accounts_v1beta/merchantapi-gen.go
  merchantapi/conversions_v1beta/merchantapi-api.json
  merchantapi/conversions_v1beta/merchantapi-gen.go
  merchantapi/datasources_v1beta/merchantapi-api.json
  merchantapi/datasources_v1beta/merchantapi-gen.go
  merchantapi/inventories_v1beta/merchantapi-api.json
  merchantapi/inventories_v1beta/merchantapi-gen.go
  merchantapi/lfp_v1beta/merchantapi-api.json
  merchantapi/lfp_v1beta/merchantapi-gen.go
  merchantapi/notifications_v1beta/merchantapi-api.json
  merchantapi/notifications_v1beta/merchantapi-gen.go
  merchantapi/products_v1beta/merchantapi-api.json
  merchantapi/products_v1beta/merchantapi-gen.go
  merchantapi/promotions_v1beta/merchantapi-api.json
  merchantapi/promotions_v1beta/merchantapi-gen.go
  merchantapi/quota_v1beta/merchantapi-api.json
  merchantapi/quota_v1beta/merchantapi-gen.go
  merchantapi/reports_v1beta/merchantapi-api.json
  merchantapi/reports_v1beta/merchantapi-gen.go
  migrationcenter/v1alpha1/migrationcenter-api.json
  migrationcenter/v1alpha1/migrationcenter-gen.go
  pubsub/v1/pubsub-api.json
  pubsub/v1/pubsub-gen.go
  serviceconsumermanagement/v1beta1/serviceconsumermanagement-api.json
  serviceconsumermanagement/v1beta1/serviceconsumermanagement-gen.go
  spanner/v1/spanner-api.json
  spanner/v1/spanner-gen.go
  vault/v1/vault-api.json
  vault/v1/vault-gen.go
Labels: automerge: exact

#2644 feat(all): auto-regenerate discovery clients
  admin/directory/v1/admin-api.json
  admin/directory/v1/admin-gen.go
  assuredworkloads/v1/assuredworkloads-api.json
  assuredworkloads/v1/assuredworkloads-gen.go
  assuredworkloads/v1beta1/assuredworkloads-api.json
  assuredworkloads/v1beta1/assuredworkloads-gen.go
  cloudasset/v1/cloudasset-api.json
  cloudasset/v1/cloudasset-gen.go
  cloudbuild/v2/cloudbuild-api.json
  cloudbuild/v2/cloudbuild-gen.go
  dialogflow/v2/dialogflow-api.json
  dialogflow/v2/dialogflow-gen.go
  dialogflow/v2beta1/dialogflow-api.json
  dialogflow/v2beta1/dialogflow-gen.go
  dlp/v2/dlp-api.json
  dlp/v2/dlp-gen.go
  games/v1/games-api.json
  games/v1/games-gen.go
  groupssettings/v1/groupssettings-api.json
  groupssettings/v1/groupssettings-gen.go
  kmsinventory/v1/kmsinventory-api.json
  kmsinventory/v1/kmsinventory-gen.go
  monitoring/v1/monitoring-api.json
  monitoring/v1/monitoring-gen.go
Labels: automerge: exact

#2633 chore: add simple readme for generator
  google-api-go-generator/README.md
Labels: automerge

#2645 feat(all): auto-regenerate discovery clients
  apigee/v1/apigee-api.json
  apigee/v1/apigee-gen.go
  bigqueryreservation/v1/bigqueryreservation-api.json
  container/v1/container-api.json
  container/v1/container-gen.go
  container/v1beta1/container-api.json
  container/v1beta1/container-gen.go
  containeranalysis/v1/containeranalysis-api.json
  containeranalysis/v1alpha1/containeranalysis-api.json
  containeranalysis/v1beta1/containeranalysis-api.json
  datacatalog/v1/datacatalog-api.json
  datacatalog/v1/datacatalog-gen.go
  datacatalog/v1beta1/datacatalog-api.json
  datacatalog/v1beta1/datacatalog-gen.go
  securitycenter/v1/securitycenter-api.json
  securitycenter/v1/securitycenter-gen.go
  securitycenter/v1beta1/securitycenter-api.json
  securitycenter/v1beta1/securitycenter-gen.go
  securitycenter/v1beta2/securitycenter-api.json
  securitycenter/v1beta2/securitycenter-gen.go
  vmmigration/v1/vmmigration-api.json
  vmmigration/v1/vmmigration-gen.go
  vmmigration/v1alpha1/vmmigration-api.json
  vmmigration/v1alpha1/vmmigration-gen.go
Labels: automerge: exact

#2648 feat(all): auto-regenerate discovery clients
  beyondcorp/v1alpha/beyondcorp-api.json
  beyondcorp/v1alpha/beyondcorp-gen.go
  binaryauthorization/v1/binaryauthorization-api.json
  binaryauthorization/v1/binaryauthorization-gen.go
  container/v1beta1/container-api.json
  container/v1beta1/container-gen.go
  dataproc/v1/dataproc-api.json
  dataproc/v1/dataproc-gen.go
  networkmanagement/v1/networkmanagement-api.json
  networkmanagement/v1/networkmanagement-gen.go
  networkmanagement/v1beta1/networkmanagement-api.json
  networkmanagement/v1beta1/networkmanagement-gen.go
  run/v2/run-api.json
  run/v2/run-gen.go
  workloadmanager/v1/workloadmanager-api.json
  workloadmanager/v1/workloadmanager-gen.go
Labels: automerge: exact

#2649 feat(all): auto-regenerate discovery clients
  api-list.json
  bigquerydatatransfer/v1/bigquerydatatransfer-api.json
  clouddeploy/v1/clouddeploy-api.json
  clouddeploy/v1/clouddeploy-gen.go
  cloudkms/v1/cloudkms-api.json
  cloudkms/v1/cloudkms-gen.go
  contactcenteraiplatform/v1alpha1/contactcenteraiplatform-api.json
  contactcenteraiplatform/v1alpha1/contactcenteraiplatform-gen.go
  networkservices/v1/networkservices-api.json
  networkservices/v1/networkservices-gen.go
  networkservices/v1beta1/networkservices-api.json
  networkservices/v1beta1/networkservices-gen.go
  redis/v1/redis-api.json
  redis/v1/redis-gen.go
  redis/v1beta1/redis-api.json
  redis/v1beta1/redis-gen.go
Labels: automerge: exact

#2652 feat(all): auto-regenerate discovery clients
  alloydb/v1/alloydb-api.json
  alloydb/v1/alloydb-gen.go
  alloydb/v1alpha/alloydb-api.json
  alloydb/v1alpha/alloydb-gen.go
  alloydb/v1beta/alloydb-api.json
  alloydb/v1beta/alloydb-gen.go
  datafusion/v1/datafusion-api.json
  datafusion/v1/datafusion-gen.go
  datafusion/v1beta1/datafusion-api.json
  datafusion/v1beta1/datafusion-gen.go
  firestore/v1/firestore-api.json
  firestore/v1/firestore-gen.go
  firestore/v1beta1/firestore-api.json
  firestore/v1beta1/firestore-gen.go
  firestore/v1beta2/firestore-api.json
  firestore/v1beta2/firestore-gen.go
  storage/v1/storage-api.json
  storage/v1/storage-gen.go
Labels: automerge: exact

#2653 feat(all): auto-regenerate discovery clients
  accesscontextmanager/v1/accesscontextmanager-api.json
  accesscontextmanager/v1/accesscontextmanager-gen.go
  androidenterprise/v1/androidenterprise-api.json
  androidenterprise/v1/androidenterprise-gen.go
  androidpublisher/v3/androidpublisher-api.json
  androidpublisher/v3/androidpublisher-gen.go
  classroom/v1/classroom-api.json
  classroom/v1/classroom-gen.go
  container/v1/container-api.json
  container/v1/container-gen.go
  networkconnectivity/v1/networkconnectivity-api.json
  networkconnectivity/v1/networkconnectivity-gen.go
  sqladmin/v1/sqladmin-api.json
  sqladmin/v1/sqladmin-gen.go
  sqladmin/v1beta4/sqladmin-api.json
  sqladmin/v1beta4/sqladmin-gen.go
Labels: automerge: exact

#2654 chore: bump auth lib dep
  go.mod
  go.sum
Labels: automerge

#2658 feat(all): auto-regenerate discovery clients
  analyticshub/v1/analyticshub-api.json
  analyticshub/v1/analyticshub-gen.go
  analyticshub/v1beta1/analyticshub-api.json
  analyticshub/v1beta1/analyticshub-gen.go
  chat/v1/chat-api.json
  chat/v1/chat-gen.go
  containeranalysis/v1/containeranalysis-api.json
  containeranalysis/v1/containeranalysis-gen.go
  containeranalysis/v1alpha1/containeranalysis-api.json
  containeranalysis/v1alpha1/containeranalysis-gen.go
  dataflow/v1b3/dataflow-api.json
  dataflow/v1b3/dataflow-gen.go
  dialogflow/v3beta1/dialogflow-api.json
  dialogflow/v3beta1/dialogflow-gen.go
  factchecktools/v1alpha1/factchecktools-api.json
  factchecktools/v1alpha1/factchecktools-gen.go
  pubsub/v1/pubsub-api.json
  pubsub/v1/pubsub-gen.go
  storagetransfer/v1/storagetransfer-api.json
  storagetransfer/v1/storagetransfer-gen.go
Labels: automerge: exact

#2657 fix(gensupport): wrap chunk upload err for retries
  internal/gensupport/resumable.go
Labels: automerge

#2660 feat(all): auto-regenerate discovery clients
  api-list.json
  bigquery/v2/bigquery-api.json
  bigquery/v2/bigquery-gen.go
  chat/v1/chat-api.json
  chat/v1/chat-gen.go
  container/v1beta1/container-api.json
  container/v1beta1/container-gen.go
  file/v1/file-api.json
  file/v1/file-gen.go
  file/v1beta1/file-api.json
  file/v1beta1/file-gen.go
  healthcare/v1/healthcare-api.json
  healthcare/v1/healthcare-gen.go
  healthcare/v1beta1/healthcare-api.json
  healthcare/v1beta1/healthcare-gen.go
  logging/v2/logging-api.json
  logging/v2/logging-gen.go
  storage/v1/storage-api.json
  workloadmanager/v1/workloadmanager-api.json
  workloadmanager/v1/workloadmanager-gen.go
  workstations/v1/workstations-api.json
  workstations/v1/workstations-gen.go
  workstations/v1beta/workstations-api.json
  workstations/v1beta/workstations-gen.go
Labels: automerge: exact

#2661 feat(all): auto-regenerate discovery clients
  beyondcorp/v1alpha/beyondcorp-api.json
  beyondcorp/v1alpha/beyondcorp-gen.go
Labels: automerge: exact
